# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikeways', '0002_bikeway_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeway',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bikeways', to='bikeways.BikewayCategory'),
        ),
    ]
